# Generated by Django 4.2.4 on 2023-08-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveIntegerField(verbose_name='company_id')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('driver_id', models.PositiveIntegerField(verbose_name='driver_id')),
                ('status', models.CharField(choices=[('s', 'start'), ('f', 'finish'), ('o', 'off')], default='o', max_length=1, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['driver_id'],
            },
        ),
    ]
